language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install mock
  - pip install coveralls
  - pip install codeclimate-test-reporter

script:
  coverage run --source=rostam -m unittest discover -s tests -p "*.py"

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter
