language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=rostam -m unittest discover -s tests -p "*.py"

after_success:
  coveralls
